version: "3.9"

services:
  minio:
    image: aerospike.jfrog.io/ecosystem-dockerhub-mirror/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f  http://localhost:9001 || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 5s
    environment:
      - "MINIO_ACCESS_KEY=minioadmin"
      - "MINIO_SECRET_KEY=minioadmin"
    command: server /data --console-address ":9001"

  createbucket:
    image: aerospike.jfrog.io/ecosystem-dockerhub-mirror/minio/mc:latest
    container_name: createbucket
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/as-backup-bucket;
      /usr/bin/mc anonymous set public myminio/as-backup-bucket;
      exit 0;
      "