plugin: google.cloud.gcp_compute

projects:
  - ${PROJECT}

filters:
  - status = RUNNING
  - labels.workspace = ${WORKSPACE}
  - labels.service = ${MODULE_NAME}

auth_kind: application

scopes:
  - 'https://www.googleapis.com/auth/cloud-platform'
  - 'https://www.googleapis.com/auth/compute.readonly'

keyed_groups:
  - prefix: ${WORKSPACE}-asdb
    key: labels

hostnames:
  - name

compose:
  ansible_host: selfLink
