{
 "title": "Summit Talk 3",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"aerospike\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"aerospike\", cluster_name=~\"$cluster|$^\"},service)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_namespace_objects{job=\"aerospike\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },ns)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "aerospike_namespace_rack_id", "legendFormat": "{{service}}-{{tags}}" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aerospike_namespace_master_objects ",
     "legendFormat": "{{service}}-{{tags}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aerospike_namespace_prole_objects ",
     "legendFormat": "{{service}}-{{tags}}"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_node_up{job=\"aerospike\", cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Read + Total Write (Server Side)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aerospike_namespace_client_read_success{job=\"aerospike\",cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[1m]))",
     "legendFormat": "Total Read Success"
    },
    {
     "expr": "sum(rate(aerospike_namespace_client_write_success{job=\"aerospike\",cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[1m])) ",
     "legendFormat": "Total Write Success"
    }
   ]
  },
  {
   "title": "Total Master Objects",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_master_objects{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) "
    }
   ]
  },
  {
   "title": "Migrations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_migrate_rx_partitions_remaining{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aerospike_node_up{job=\"aerospike\", cluster_name=~\"$cluster\"})",
     "legendFormat": "Cluster Size"
    }
   ]
  },
  {
   "title": "Migrations Remaining",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aerospike_namespace_migrate_rx_partitions_remaining{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Migrations remaining"
    }
   ]
  },
  {
   "title": "Server Read/Write timeout/error/not found",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aerospike_namespace_client_read_error{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]))",
     "legendFormat": "server read error rate"
    },
    {
     "expr": "sum(rate(aerospike_namespace_client_read_timeout{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]))",
     "legendFormat": "server read timeout rate"
    },
    {
     "expr": "sum(rate(aerospike_namespace_client_read_not_found{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]))",
     "legendFormat": "server read not found error rate"
    },
    {
     "expr": "sum(rate(aerospike_namespace_client_write_error{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]))",
     "legendFormat": "server write error rate"
    },
    {
     "expr": "sum(rate(aerospike_namespace_client_write_timeout{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]))",
     "legendFormat": "server write timeout rate"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aerospike_client_read_errors[1m]) ",
     "legendFormat": "client read error rate"
    },
    {
     "expr": "rate(aerospike_client_read_timeouts[1m]) ",
     "legendFormat": "client read timeout rate"
    },
    {
     "expr": "rate(aerospike_client_write_errors[1m]) ",
     "legendFormat": "ciient write error rate"
    },
    {
     "expr": "rate(aerospike_client_read_timeouts[1m]) ",
     "legendFormat": "client write timeout rate"
    }
   ]
  }
 ]
}