- block:
    - name: "Get Encryption Key"
      google.cloud.gcp_secret_manager:
        name: "features-conf"
        state: present
        project: "{{ project_id }}"
        auth_kind: "application"
      delegate_to: localhost
      run_once: true
      become: no
      register: encryption_key
      when: encryption_at_rest | bool

    - name: "Copy Encryption Key"
      copy:
        dest: "{{ aerospike.config_dir }}/encryption.aes-256.key.pem"
        content: "{{ encryption_key.value }}"
        mode: "0644"
        owner: "root"
        group: "root"
      when: encryption_at_rest | bool

    - name: "Get Features Conf"
      google.cloud.gcp_secret_manager:
        name: "features-conf"
        state: present
        project: "{{ project_id }}"
        auth_kind: "application"
      delegate_to: localhost
      run_once: true
      become: no
      register: features_conf

    - name: "Copy Features Conf"
      copy:
        dest: "{{ aerospike.config_dir }}/features.conf"
        content: "{{ features_conf.value }}"
        mode: "0644"
        owner: "root"
        group: "root"

    - block:
        - name: "Get TLS ASD Public Key"
          google.cloud.gcp_secret_manager:
            name: "asd-aerospike-com-pem"
            state: present
            project: "{{ project_id }}"
            auth_kind: "application"
          delegate_to: localhost
          run_once: true
          become: no
          register: asd_aerospike_com_pem

        - name: "Copy TLS ASD Public Key"
          copy:
            dest: "{{ aerospike.certs_dir }}/asd.aerospike.com.pem"
            content: "{{ asd_aerospike_com_pem.value }}"
            mode: "0644"
            owner: "root"
            group: "root"

        - name: "Get TLS ASD Private Key"
          google.cloud.gcp_secret_manager:
            name: "asd-aerospike-com-key"
            state: present
            project: "{{ project_id }}"
            auth_kind: "application"
          delegate_to: localhost
          run_once: true
          become: no
          register: asd_aerospike_com_key

        - name: "Copy TLS ASD Private Key"
          copy:
            dest: "{{ aerospike.certs_dir }}/asd.aerospike.com.key"
            content: "{{ asd_aerospike_com_key.value }}"
            mode: "0644"
            owner: "root"
            group: "root"
      when: security_type in ["TLS", "mTLS"]
