# yaml-language-server: $schema=https://raw.githubusercontent.com/aerospike/aerospike-backup-service/refs/heads/v3/docs/config.schema.json

aerospike-clusters:
  absDefaultCluster:
    seed-nodes:
      - host-name: "host.docker.internal"
        port: 3000
    credentials:
      user: "tester"
      password: "psw"
    max-parallel-scans: 20

storage:
  local:
    local-storage:
      path: /data
  minio:
    s3-storage:
      path: storage1
      bucket: as-backup-bucket
      s3-region: eu-central-1
      s3-profile: minio
      s3-endpoint-override: http://host.docker.internal:9000

backup-policies:
  defaultPolicy:
    parallel: 8
    retry-policy:
      base-timeout: 3000
      max-retries: 10
      multiplier: 1
    retention:
      full: 10
      incremental: 10
  withFileLimit:
    file-limit: 1
    parallel: 1
    retry-policy:
      base-timeout: 1000
      max-retries: 1
      multiplier: 1
    retention:
      full: 10
      incremental: 10
  withClusterConfiguration:
    with-cluster-configuration: true
    retention:
      full: 10
  withBandwidthLimit:
    bandwidth: 10
    parallel: 1
    retry-policy:
      base-timeout: 1000
      max-retries: 1
      multiplier: 1
    retention:
      full: 10
      incremental: 10
  removeFilesPolicy:
    parallel: 8
    retention:
      full: 1
      incremental: 0
  encryptedCompressedPolicy128:
    file-limit: 1
    parallel: 1
    retention:
      full: 1
      incremental: 0
    encryption:
      key-file: encryptionKey
      mode: AES128
    compression:
      level: 20
      mode: ZSTD
  encryptedCompressedPolicy256:
    parallel: 8
    retention:
      full: 1
      incremental: 0
    encryption:
      key-env: BACKUP_ENCRYPTION_KEY
      mode: AES256
    compression:
      level: 10
      mode: ZSTD
  sealed:
    parallel: 8
    sealed: true
    retention:
      full: 10
      incremental: 10
  noIndexesUdfsRecords:
    with-cluster-configuration: true
    parallel: 8
    no-indexes: true
    no-records: true
    no-udfs: true
    retention:
      full: 10
#    xdrBackup:
#        parallel: 8
#        retention:
#          full: 10
#          incremental: 10
#        xdr:
#            local-host: "host.docker.internal"
#            port-range:
#                start: 8081
#                end: 8085
backup-routines:
  localStorage:
    interval-cron: "@yearly"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ "source-ns2" ]
    # this routine tests that policy is optional
  localStorageSealed:
    interval-cron: "@yearly"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ "source-ns2" ]
    backup-policy: sealed
  minio:
    interval-cron: "@yearly"
    source-cluster: absDefaultCluster
    storage: minio
    namespaces: [ "source-ns4" ]
    backup-policy: defaultPolicy
  localStorageIncremental1:
    interval-cron: "@yearly"
    incr-interval-cron: "*/10 * * * * *"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ "source-ns5" ]
    set-list:
      - absSet5
    backup-policy: defaultPolicy
  incrementalBackupCluster:
    interval-cron: "@yearly"
    incr-interval-cron: "*/10 * * * * *"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ ]
    backup-policy: defaultPolicy
  incrementalBackupClusterSealed:
    interval-cron: "@yearly"
    incr-interval-cron: "*/10 * * * * *"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ ]
    backup-policy: sealed
  incrementalBackupMultipleNSs:
    interval-cron: "@yearly"
    incr-interval-cron: "*/10 * * * * *"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ "source-ns18", "source-ns19", "source-ns20" ]
    backup-policy: defaultPolicy
  edgeCases:
    interval-cron: "@yearly"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ "source-ns7" ]
    backup-policy: defaultPolicy
  filterBySetAndBin:
    interval-cron: "@yearly"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ "source-ns8" ] # don't truncate full source-ns8 in any tests
    set-list:
      - backupSet
    bin-list:
      - backupBin
    backup-policy: defaultPolicy
  localStorageIncremental3:
    interval-cron: "@yearly"
    incr-interval-cron: "*/10 * * * * *"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ "source-ns10" ]
    backup-policy: defaultPolicy
  fullBackup1:
    interval-cron: "@yearly"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ "source-ns9" ]
    backup-policy: defaultPolicy
  fullBackup2:
    interval-cron: "@yearly"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ "source-ns11" ]
    backup-policy: withFileLimit
  fullBackup3:
    interval-cron: "@yearly"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ "source-ns12" ]
    backup-policy: defaultPolicy
  fullBackupFullCluster:
    interval-cron: "@yearly"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ ]
    backup-policy: defaultPolicy
  fullBackup3Namespaces:
    interval-cron: "@yearly"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ "source-ns15", "source-ns16", "source-ns17" ]
    backup-policy: defaultPolicy
  timestamp:
    interval-cron: "@yearly"
    incr-interval-cron: "*/10 * * * * *"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ "source-ns14" ]
    backup-policy: defaultPolicy
  fullBackupSlow:
    interval-cron: "@yearly"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ "source-ns13" ]
    backup-policy: withBandwidthLimit
  fullBackupEncryptedCompressed128:
    interval-cron: "@yearly"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ "source-ns18" ]
    backup-policy: encryptedCompressedPolicy128
  fullBackupEncryptedCompressed256:
    interval-cron: "@yearly"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ "source-ns21" ]
    backup-policy: encryptedCompressedPolicy256
  noIndexesUdfsRecords:
    interval-cron: "@yearly"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ "source-ns19" ]
    backup-policy: noIndexesUdfsRecords
  oneMinuteIntervalBackup:
    interval-cron: "0 */1 * * * *"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ "source-ns20" ]
    backup-policy: defaultPolicy
  everySecondBackup:
    backup-policy: defaultPolicy
    source-cluster: absDefaultCluster
    storage: local
    interval-cron: '* * * * * *'
    incr-interval-cron: ""
    namespaces:
      - source-ns20
    disabled: true
  #    xdrBackup:
  #        interval-cron: "@yearly"
  #        incr-interval-cron: "0 */1 * * * *" # every minute incremental backup
  #        source-cluster: absDefaultCluster
  #        storage: local
  #        namespaces: [ "source-ns22" ]
  #        backup-policy: xdrBackup
  incrementalBackupEncryptedCompressed128:
    interval-cron: "@yearly"
    incr-interval-cron: "*/10 * * * * *"
    source-cluster: absDefaultCluster
    storage: local
    namespaces: [ "source-ns23" ]
    backup-policy: encryptedCompressedPolicy128

service:
  logger:
    level: INFO
    file-writer:
      filename: "/var/log/aerospike-backup-service/aerospike-backup-service.log"
