- name: Get cluster ip addresses
  set_fact:
    cluster_ip_addresses: "[]"
    client_ip_addresses: []

- name: Get cluster ip addresses
  set_fact:
    cluster_ip_addresses: "{{ cluster_ip_addresses }} + [ '{{ hostvars[item].ansible_host }}' ]"
  with_items: 
    "{{ groups[cluster_tag] }}"

- name: Get client ip addresses
  set_fact:
    client_ip_addresses: "{{ client_ip_addresses }} + [ '{{ hostvars[item].private_ip_address }}' ]"
  when: groups[client_tag] is defined
  with_items: 
    "{{ groups[client_tag]}}"

- name: Prometheus config file
  template:
    src: "assets/prometheus.yml.j2"
    dest: "{{prometheus_config_directory}}/prometheus.yml"
    mode: '0644'
    owner: root
    group: root    
