apiVersion: 1

datasources:
- name: "Aerospike Prometheus Alertmanager"
  type: camptocamp-prometheus-alertmanager-datasource
  access: proxy
  url: http://localhost:9093
  editable: true
  isDefault: false

- name: "Aerospike Prometheus"
  type: prometheus
  access: proxy
  url: http://localhost:9090
  editable: true
  isDefault: false
