name: Build Release Docker Images
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version tag
      commit:
        required: true
        description: Commit ID
      timestamp:
        required: true
        description: Timestamp in iso8601
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Automation Code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup Jfrog
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
      - name: Login to JFrog
        uses: docker/login-action@v2
        with:
          registry: aerospike.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_TOKEN }}
      - name: Build and Push
        uses: docker/bake-action@v4
        env:
          CACHEBUST: 1
          TAG: ${{ github.event.inputs.version }}
          GIT_BRANCH: main
          GIT_COMMIT_SHA: ${{ github.event.inputs.commit }}
          VERSION: ${{ github.event.inputs.version }}
          ISO8601: ${{ github.event.inputs.timestamp }}
        with:
          workdir: ${{ github.workspace }}/devops/backup-service/build/docker
          files: docker-bake.hcl
          targets: default
      - name: Promote image with version tag
        env:
          ARTIFACTORY_CONTAINER_DEV: ${{ vars.ARTIFACTORY_CONTAINER_DEV }}
          ARTIFACTORY_CONTAINER_PROD: ${{ vars.ARTIFACTORY_CONTAINER_PROD }}
        run: |
          jfrog rt docker-promote aerospike-backup-service \
          "$ARTIFACTORY_CONTAINER_DEV" \
          "$ARTIFACTORY_CONTAINER_PROD" \
          --source-tag "${{ github.event.inputs.version }}" \
          --target-tag "${{ github.event.inputs.version }}" \
          --user "${{ secrets.ARTIFACTORY_USER }}" \
          --password "${{ secrets.ARTIFACTORY_TOKEN }}" \
          --url "${{ secrets.ARTIFACTORY_PROMOTE_URL }}" \
          --copy
      - name: Promote image with latest tag
        env:
          ARTIFACTORY_CONTAINER_DEV: ${{ vars.ARTIFACTORY_CONTAINER_DEV }}
          ARTIFACTORY_CONTAINER_PROD: ${{ vars.ARTIFACTORY_CONTAINER_PROD }}
        run: |
          jfrog rt docker-promote aerospike-backup-service \
          "$ARTIFACTORY_CONTAINER_DEV" \
          "$ARTIFACTORY_CONTAINER_PROD" \
          --source-tag "${{ github.event.inputs.version }}" \
          --target-tag "latest" \
          --user "${{ secrets.ARTIFACTORY_USER }}" \
          --password "${{ secrets.ARTIFACTORY_TOKEN }}" \
          --url "${{ secrets.ARTIFACTORY_PROMOTE_URL }}" \
          --copy

